### PR TITLE
Added the option to enable SSL verification

### LINKED ISSUE #133: SSL verification disabled, without option to enable
On debian stretch I get warnings:
`/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
`
I found at https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/icontrol/authtoken.py#L98
the request is made with verify=False. It would be nice to be able to change this setting through F5 libraries to be able to verify ssl.
Anyway thank you for great work to make icontrol available from python.

### PR DESCRIPTION
**Pull request by magnuswatn**
Issues:
Fixes #133

Problem:
It was not possible for the caller to turn on certificate verification

Analysis:
Makes the verify option from requests available to the caller

Tests:
Added both unit tests and functional testcases to check that the certificate is now correctly checked (when the caller wants)

### CODE REVIEW

**Comment by dflanigan** [comment]
@zancas and @wojtek0806: @magnuswatn  has filled out a CLA for us and we can accept his contributions.

**Comment by magnuswatn** [comment]
What's the status here? Just give me a heads up if there's anything I should change.

The failing Travis build is because sphinx/typing have dropped Python 2.6 support.

**Comment by caphrim007** [comment]
lgtm

**Comment by caphrim007** [comment]
suppose we should fix the travis tests in a follow-up PR to not test on 2.6 anymore. f5-sdk doesn't support 2.6 anymore either

**Comment by magnuswatn** [comment]
Would it be possible to release a new version with this included? Need it to add the verify functionality to f5-common-python.

**Comment by caphrim007** [comment]
@magnuswatn I am going to pressure the release team to do this starting tomorrow

**Comment by caphrim007** [comment]
@zancas @pjbreaux please assist with a release

**Comment by caphrim007** [comment]
@magnuswatn i believe this is now released with f5-sdk 3.0

**Comment by magnuswatn** [comment]
@caphrim007 I'm not sure i understand. Isn't f5-sdk (f5-common-python) another package, which is just dependent on this one? I don't see how a release of f5-sdk is relevant to fixes here? I tried to download a fresh copy of f5-sdk, and I got the old f5-icontrol-rest code.

Sorry if I'm missing something obvious here.

**Pull request merged**
