### PR TITLE
Feature.token auth rebased

### PR DESCRIPTION
**Pull request by zancas**
Rebase fixup.

Oooopsss...  merged into the wrong branch somehow!!

@andrewjjenkins --^

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can you also make the requests version in setup.py >= 2.5.1 or >= 2.7.0?

**Comment by pjbreaux** [comment]
Version 2.5.0!

**Comment by zancas** [comment]
@pjbreaux done.

**Comment by pjbreaux** [comment]
Ok Merging.

**Pull request merged**
